import type { Metadata } from "next";
import { Inter, Rethink_Sans } from "next/font/google";
import "./globals.css";
import Lenis from "@/components/Lenis";

const inter = Inter({ subsets: ["latin"] });
const rethink = Rethink_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rethink.className}>
        <Lenis>
          {children}
        </Lenis>
      </body>
    </html>
  );
}
